# Generated by Django 5.0.7 on 2024-08-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='plan_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
