# Generated by Django 5.0.7 on 2024-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todoitem_plan_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='plan_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
